disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: ''

menu:
- {name: 'About', path: '.', url: 'index.html'}
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'Teaching', path: 'menu', url: 'teaching.html'}
- {name: 'Education', path: 'menu', url: 'education.html'}

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/tatiana-labuzova-2b016438/'}
- {icon: 'envelope', link: 'mailto:labuzova@mit.edu'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'
sharing_button_prompt: 'Feel free to share!'
related_posts: 'You may also enjoy:'
post_date_prefix: 'Written on'
